export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const GET_MOCK_TODOS_SUCCESS = 'GET_MOCK_TODOS_SUCCESS';
export const GET_MOCK_TODOS_ERROR = 'GET_MOCK_TODOS_ERROR';
